Integrantes:
- Douglas Ardila Garcés
- Natalia Arias Lozano
- Andrés Felipe Avendaño
- Camila White Romero

# Punto 2

# Punto 3

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

### 1. Implementar el algoritmo de clasificación KNN. Valide con los datos del problema 1 (el de calentamiento).

In [2]:
X = np.array([[0.8, 0.8], [0.8, 1.2], [3.8, 2.8], [4.2, 3.2], [1, 1], [1.2, 1.2], [4.2, 2.8], [4.4, 2.8], 
              [3.5, 1], [4, 1],[3.8, 0.5], [4, 0.7]])
Y = np.array([1, 1, 2, 2, 1, 1, 2, 2, 3, 3, 3, 3])

In [3]:
data = pd.DataFrame(X, columns=['x1', 'x2'])
data['y'] = Y
data.head()

x1   x2  y
0  0.8  0.8  1
1  0.8  1.2  1
2  3.8  2.8  2
3  4.2  3.2  2
4  1.0  1.0  1

In [4]:
X = data[['x1', 'x2']]
y = data['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [6]:
predictions

array([2, 2, 1, 2])

In [7]:
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

Accuracy: 0.25


### 2. Para este ejercicio use la base de datos DatosFisher.xlsx disponible en la página del curso.

In [8]:
dataFisher = pd.read_excel('DatosFisher.xlsx', skiprows=1)
dataFisher.head()

sexo  estatura  peso  longitudpie  longitudbrazo  anchuraespalda  \
0     0       159    49         36.0           68.0            42.0   
1     1       164    62         39.0           73.0            44.0   
2     0       172    65         38.0           75.0            48.0   
3     1       167    52         37.0           73.0            41.5   
4     1       164    51         36.0           71.0            44.5   

   diametrocraneo  longitudrodillatobillo  
0            57.0                    40.0  
1            55.0                    44.0  
2            58.0                    44.0  
3            58.0                    44.0  
4            54.0                    40.0

In [9]:
X = dataFisher.drop(['sexo'], axis=1)
y = dataFisher['sexo']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [11]:
predictions

array([1, 1, 0, 0, 0, 1, 0, 0, 0])

In [12]:
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

Accuracy: 0.7777777777777778


### 3. Seleccione el k para el cual el error de entrenamiento sea mínimo. k =?

In [13]:
for k in range(1,10):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    print("Accuracy for", k, "is: ", metrics.accuracy_score(y_test, predictions))

Accuracy for 1 is:  0.8888888888888888
Accuracy for 2 is:  0.5555555555555556
Accuracy for 3 is:  0.6666666666666666
Accuracy for 4 is:  0.7777777777777778
Accuracy for 5 is:  0.8888888888888888
Accuracy for 6 is:  0.5555555555555556
Accuracy for 7 is:  0.7777777777777778
Accuracy for 8 is:  0.6666666666666666
Accuracy for 9 is:  0.8888888888888888


El k para el cual el error de entrenamiento es mínimo, es k=5.

# Punto 5

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import kurtosis

In [2]:
data = pd.read_excel('ELE.xlsx', header=None)  
data.head()

0       1       2         3        4          5       6         7   \
0  82.23  333.65  125.95  12231.27  1110.97  105069.63  263.66  77811.79   
1  79.17  349.29  120.41  11977.18  1069.27  107210.46  261.29  69254.01   
2  79.92  342.56  113.92  11712.42   997.68  108138.53  262.07  55266.32   
3  75.83  299.48  163.12  11539.83  1003.56  110735.68  264.49  40753.72   
4  78.72  268.19  119.30  11289.02   976.19  110619.01  262.18  54150.28   

       8          9          10      11      12       13        14       15  \
0  423.50  112743.19  823200.19  403.91  982.62  3955.22  19381.56  4324.97   
1  435.26   98112.25  705245.02  400.45  962.11  3946.92  17222.31  4262.06   
2  422.36   84301.39  603368.98  392.59  944.62  3981.55  14876.55  4260.74   
3  419.72   75501.86  540643.37  383.81  928.89  3992.56  13453.31  4374.65   
4  412.30   68409.14  499768.04  379.25  912.91  3941.43  12032.98  4357.31   

          16  
0  125876.24  
1  111311.84  
2   98425.38  
3   88527.77  
4   81449.29

In [3]:
m = data.shape[0]
one = np.ones((m,1))

### 1. Estudiar el tipo de variable de manera univariante.

In [4]:
data.describe()

0           1           2             3            4   \
count  24.000000   24.000000   24.000000     24.000000    24.000000   
mean   69.569167  266.415833   86.936250  12547.755000  1203.770417   
std     8.134553   38.848184   33.739803   1236.273447   173.740257   
min    55.880000  214.260000   -0.360000  10437.330000   930.020000   
25%    63.225000  239.472500   72.347500  11619.532500  1055.085000   
50%    69.100000  256.100000   92.630000  12668.045000  1242.570000   
75%    76.920000  287.705000  106.532500  13383.467500  1358.237500   
max    82.230000  349.290000  163.120000  14734.770000  1480.070000   

                  5           6             7           8              9   \
count      24.000000   24.000000     24.000000   24.000000      24.000000   
mean   113199.392500  235.588333  55842.805417  593.431667   82134.531250   
std      5622.010113   26.054715  13653.273898  152.193128   19136.279173   
min    105069.630000  204.570000  40753.720000  315.430000   54032.480000   
25%    109235.005000  209.025000  46561.625000  423.215000   68393.597500   
50%    111255.150000  233.735000  51969.080000  653.685000   75912.280000   
75%    117980.042500  262.422500  59133.875000  698.725000   86368.270000   
max    123542.560000  267.300000  92492.590000  824.530000  131999.850000   

                  10          11          12           13            14  \
count      24.000000   24.000000   24.000000    24.000000     24.000000   
mean   599689.956250  601.732500  925.003750  2629.052083  14387.621667   
std    134450.219602  180.540165   39.084121  1472.053564   2991.939096   
min    431534.830000  379.250000  869.230000   946.110000  10894.730000   
25%    507572.630000  403.902500  894.130000  1220.525000  12634.757500   
50%    560832.480000  599.985000  925.985000  2636.155000  13177.435000   
75%    631338.452500  767.895000  954.780000  4014.565000  15462.990000   
max    903238.970000  862.310000  995.990000  4272.590000  21404.120000   

                15             16  
count    24.000000      24.000000  
mean   3878.305000  102866.145000  
std     777.095562   28673.141354  
min    2876.350000   74031.670000  
25%    3203.535000   85085.770000  
50%    3752.750000   92409.750000  
75%    4437.942500  111634.527500  
max    5245.480000  174154.020000

Curtosis

In [5]:
kurtosis(data)

array([-1.33631823, -0.41679567,  0.83789888, -0.94935956, -1.34452428,
       -0.93677626, -1.83356592,  0.5090123 , -1.17579249,  0.43933698,
       -0.22841013, -1.60304349, -0.96607489, -1.97465921, -0.13484978,
       -1.46473807,  0.74873281])

Varianza

In [6]:
data.var()

0     6.617095e+01
1     1.509181e+03
2     1.138374e+03
3     1.528372e+06
4     3.018568e+04
5     3.160700e+07
6     6.788482e+02
7     1.864119e+08
8     2.316275e+04
9     3.661972e+08
10    1.807686e+10
11    3.259475e+04
12    1.527569e+03
13    2.166942e+06
14    8.951700e+06
15    6.038775e+05
16    8.221490e+08
dtype: float64

La mayoria de las variables presentan una dispersión alta, esto se puede identificar debido a que la variabilidad tiene una magnitud significativa y la curtosis es menor a 0; por lo tanto puede ocurrir poca concentración de datos en la media. 

Las variables del dataset se encuentran en diferentes escalas, lo cual puede afectar la precisión del modelo.

### 2. Calcular las medidas de centralización: el vector de medias.

Fórmula $\overline{X}=\frac{1}{m}X^t1$

In [7]:
media = np.dot(1/m,data.T).dot(one)
media.tolist()

[[69.56916666666666],
 [266.41583333333335],
 [86.93625],
 [12547.755],
 [1203.7704166666667],
 [113199.3925],
 [235.5883333333333],
 [55842.80541666666],
 [593.4316666666666],
 [82134.53125],
 [599689.9562499999],
 [601.7325],
 [925.0037499999999],
 [2629.052083333333],
 [14387.621666666666],
 [3878.3049999999994],
 [102866.14499999999]]

### 3. Calcular la matriz de varianzas y covarianzas.

Con fórmula
$$P=I-\frac{1}{m}11^t$$
$$S=\frac{1}{m}X^tPX$$

In [8]:
P = np.eye(m)-(np.dot((1/m),one).dot(one.T))

In [9]:
S = np.dot((1/m),data.T).dot(P).dot(data)
S

array([[ 6.34138243e+01,  1.29404734e+02,  1.31144168e+02,
        -1.36629752e+03, -3.77258783e+02, -2.29021056e+04,
         1.34331857e+02,  5.89271128e+04, -3.92280599e+02,
         7.47337229e+04,  4.79474939e+05, -8.22213360e+02,
         1.64663740e+01,  8.06172401e+03,  1.09356647e+04,
         3.42184255e+03,  8.71150158e+04],
       [ 1.29404734e+02,  1.44629882e+03,  6.93372184e+02,
        -1.17335569e+04, -2.63103951e+03, -8.67740787e+04,
         4.14540201e+02,  1.24167510e+04, -2.07486861e+03,
         2.51739810e+04,  4.92077451e+05, -2.80180583e+03,
         2.94765703e+02,  2.27405196e+04,  1.08248196e+04,
         9.18902297e+03, -8.07253657e+04],
       [ 1.31144168e+02,  6.93372184e+02,  1.09094205e+03,
        -1.30626252e+04, -2.83039529e+03, -7.46646008e+04,
         4.82355865e+02,  2.21221081e+04, -2.43781837e+03,
         2.91395534e+04,  3.95361424e+05, -3.82958840e+03,
         2.30770727e+02,  2.43992013e+04,  1.43979403e+04,
         1.03479591e+04, -1.8

### 4. Centralizar los datos y calcular la matriz de varianzas y covarianzas.

Con fórmula
$$\tilde{X}=X − 1\overline{X^t}$$
$$S=\frac{1}{m}\tilde{X^t}\tilde{X}$$

In [10]:
XCentrada = data-one.dot(media.T)

In [11]:
S = np.dot(1/m, XCentrada.T).dot(XCentrada)
S

array([[ 6.34138243e+01,  1.29404734e+02,  1.31144168e+02,
        -1.36629752e+03, -3.77258783e+02, -2.29021056e+04,
         1.34331857e+02,  5.89271128e+04, -3.92280599e+02,
         7.47337229e+04,  4.79474939e+05, -8.22213360e+02,
         1.64663740e+01,  8.06172401e+03,  1.09356647e+04,
         3.42184255e+03,  8.71150157e+04],
       [ 1.29404734e+02,  1.44629882e+03,  6.93372184e+02,
        -1.17335569e+04, -2.63103951e+03, -8.67740787e+04,
         4.14540201e+02,  1.24167510e+04, -2.07486861e+03,
         2.51739810e+04,  4.92077451e+05, -2.80180583e+03,
         2.94765703e+02,  2.27405196e+04,  1.08248196e+04,
         9.18902297e+03, -8.07253657e+04],
       [ 1.31144168e+02,  6.93372184e+02,  1.09094205e+03,
        -1.30626252e+04, -2.83039529e+03, -7.46646008e+04,
         4.82355865e+02,  2.21221081e+04, -2.43781837e+03,
         2.91395534e+04,  3.95361424e+05, -3.82958840e+03,
         2.30770727e+02,  2.43992013e+04,  1.43979403e+04,
         1.03479591e+04, -1.8

### 5. Calcular la variabilidad total y la varianza promedio.

In [18]:
diagonal = np.diag(S)

Varianza Total

In [20]:
sum(diagonal)

18684211389.65595

Varianza Promedio

In [22]:
(1/S.shape[1])*sum(diagonal)

1099071258.2150557

### 6. Calcule la varianza generalizada y la variabilidad promedio.

Varianza Generalizada

In [16]:
VG = np.linalg.det(S)
VG

5.525955295973817e+77

Variabilidad Promedio

In [23]:
VP = VG**(1/S.shape[1])
VP

37418.19089716665

### 7. Distancia de Mahalanobis Se define la distancia de Mahalanobis entre un punto y su vector de medias como

In [ ]:
from scipy.spatial import distance

In [ ]:
mahal = []
for i in range(0, m-1):
    mahal.append(distance.mahalanobis(data.iloc[[i]], media, np.linalg.inv(S)))

mahal

# Punto 6

# Punto 7

In [14]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns

In [15]:
data = pd.read_excel('ELE.xlsx', header=None)  
data.head()

0       1       2         3        4          5       6         7   \
0  82.23  333.65  125.95  12231.27  1110.97  105069.63  263.66  77811.79   
1  79.17  349.29  120.41  11977.18  1069.27  107210.46  261.29  69254.01   
2  79.92  342.56  113.92  11712.42   997.68  108138.53  262.07  55266.32   
3  75.83  299.48  163.12  11539.83  1003.56  110735.68  264.49  40753.72   
4  78.72  268.19  119.30  11289.02   976.19  110619.01  262.18  54150.28   

       8          9          10      11      12       13        14       15  \
0  423.50  112743.19  823200.19  403.91  982.62  3955.22  19381.56  4324.97   
1  435.26   98112.25  705245.02  400.45  962.11  3946.92  17222.31  4262.06   
2  422.36   84301.39  603368.98  392.59  944.62  3981.55  14876.55  4260.74   
3  419.72   75501.86  540643.37  383.81  928.89  3992.56  13453.31  4374.65   
4  412.30   68409.14  499768.04  379.25  912.91  3941.43  12032.98  4357.31   

          16  
0  125876.24  
1  111311.84  
2   98425.38  
3   88527.77  
4   81449.29

In [16]:
data_scaled = preprocessing.scale(data)
data = pd.DataFrame(data_scaled)
data.columns = ['col0', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10', 'col11', 'col12', 'col13', 'col14', 'col15', 'col16']
data.head()

col0      col1      col2      col3      col4      col5      col6  \
0  1.589902  1.767913  1.181182 -0.261505 -0.545621 -1.477161  1.100585   
1  1.205638  2.179165  1.013453 -0.471455 -0.790797 -1.088177  1.007666   
2  1.299820  2.002201  0.816961 -0.690220 -1.211711 -0.919548  1.038247   
3  0.786213  0.869418  2.306543 -0.832828 -1.177139 -0.447652  1.133126   
4  1.149129  0.046651  0.979846 -1.040067 -1.338062 -0.468850  1.042560   

       col7      col8      col9     col10     col11     col12     col13  \
0  1.643671 -1.140567  1.633911  1.698156 -1.119292  1.505866  0.920273   
1  1.003397 -1.061635  0.852902  0.801972 -1.138869  0.969814  0.914513   
2 -0.043131 -1.148219  0.115668  0.027952 -1.183342  0.512693  0.938544   
3 -1.128932 -1.165939 -0.354057 -0.448616 -1.233019  0.101572  0.946184   
4 -0.126631 -1.215741 -0.732671 -0.759173 -1.258820 -0.316084  0.910703   

      col14     col15     col16  
0  1.705030  0.587150  0.819756  
1  0.967819  0.504454  0.300886  
2  0.166930  0.502719 -0.158206  
3 -0.318993  0.652456 -0.510818  
4 -0.803922  0.629662 -0.762996

In [17]:
data.describe()

col0          col1          col2          col3          col4  \
count  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01   
mean   6.221875e-16  8.511710e-16 -5.111652e-16  7.147061e-16  9.390636e-16   
std    1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00   
min   -1.719036e+00 -1.371431e+00 -2.642985e+00 -1.743802e+00 -1.609519e+00   
25%   -7.966776e-01 -7.084714e-01 -4.416897e-01 -7.669715e-01 -8.741976e-01   
50%   -5.891626e-02 -2.712535e-01  1.723842e-01  9.939320e-02  2.281226e-01   
75%    9.230912e-01  5.597958e-01  5.932970e-01  6.905324e-01  9.081910e-01   
max    1.589902e+00  2.179165e+00  2.306543e+00  1.807086e+00  1.624507e+00   

               col5          col6          col7          col8          col9  \
count  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01   
mean  -5.181041e-16 -1.184238e-15 -2.960595e-16 -3.411623e-16  5.551115e-17   
std    1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00   
min   -1.477161e+00 -1.216113e+00 -1.128932e+00 -1.865924e+00 -1.500107e+00   
25%   -7.203212e-01 -1.041449e+00 -6.943974e-01 -1.142480e+00 -7.335006e-01   
50%   -3.532649e-01 -7.266226e-02 -2.898236e-01  4.044154e-01 -3.321481e-01   
75%    8.686344e-01  1.052067e+00  2.462306e-01  7.067202e-01  2.259999e-01   
max    1.879333e+00  1.243296e+00  2.742056e+00  1.551113e+00  2.661845e+00   

              col10         col11         col12         col13         col14  \
count  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01   
mean   4.949744e-16 -4.348374e-16  8.234154e-16 -1.017704e-16 -3.885781e-16   
std    1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00  1.021508e+00   
min   -1.277586e+00 -1.258820e+00 -1.457710e+00 -1.167851e+00 -1.192543e+00   
25%   -6.998767e-01 -1.119335e+00 -8.069205e-01 -9.774247e-01 -5.984629e-01   
50%   -2.952261e-01 -9.887467e-03  2.564608e-02  4.928955e-03 -4.131819e-01   
75%    2.404547e-01  9.401581e-01  7.782361e-01  9.614543e-01  3.671523e-01   
max    2.306264e+00  1.474364e+00  1.855306e+00  1.140507e+00  2.395573e+00   

              col15         col16  
count  2.400000e+01  2.400000e+01  
mean   1.202742e-16 -1.619075e-16  
std    1.021508e+00  1.021508e+00  
min   -1.317090e+00 -1.027256e+00  
25%   -8.869988e-01 -6.334427e-01  
50%   -1.650446e-01 -3.725190e-01  
75%    7.356548e-01  3.123819e-01  
max    1.797179e+00  2.539698e+00

In [18]:
indexes = data[(data['col4'] >= -1.60) & (data['col4'] <= -1.19)].index

In [19]:
data.loc[(data['col4'] >= -1.61) & (data['col4'] <= -0.785), 'y'] = 0
data.loc[(data['col4'] > -0.785) & (data['col4'] <= 0.438), 'y'] = 1
data.loc[(data['col4'] > -0.03) & (data['col4'] <= 0.845), 'y'] = 2
data.loc[(data['col4'] > 0.845) & (data['col4'] <= 1.66), 'y'] = 3
data.head()

col0      col1      col2      col3      col4      col5      col6  \
0  1.589902  1.767913  1.181182 -0.261505 -0.545621 -1.477161  1.100585   
1  1.205638  2.179165  1.013453 -0.471455 -0.790797 -1.088177  1.007666   
2  1.299820  2.002201  0.816961 -0.690220 -1.211711 -0.919548  1.038247   
3  0.786213  0.869418  2.306543 -0.832828 -1.177139 -0.447652  1.133126   
4  1.149129  0.046651  0.979846 -1.040067 -1.338062 -0.468850  1.042560   

       col7      col8      col9     col10     col11     col12     col13  \
0  1.643671 -1.140567  1.633911  1.698156 -1.119292  1.505866  0.920273   
1  1.003397 -1.061635  0.852902  0.801972 -1.138869  0.969814  0.914513   
2 -0.043131 -1.148219  0.115668  0.027952 -1.183342  0.512693  0.938544   
3 -1.128932 -1.165939 -0.354057 -0.448616 -1.233019  0.101572  0.946184   
4 -0.126631 -1.215741 -0.732671 -0.759173 -1.258820 -0.316084  0.910703   

      col14     col15     col16    y  
0  1.705030  0.587150  0.819756  1.0  
1  0.967819  0.504454  0.300886  0.0  
2  0.166930  0.502719 -0.158206  0.0  
3 -0.318993  0.652456 -0.510818  0.0  
4 -0.803922  0.629662 -0.762996  0.0

In [20]:
X = data.drop(['col4', 'y'], axis=1)
y = data['y'].astype(int) #Según el punto 6 es la variable más explicada por las demás

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [22]:
clf = RandomForestClassifier(max_depth=3, random_state=0)
clf.fit(X_train, y_train)
predicts = clf.predict(X_test)

In [23]:
print("Accuracy Test:",accuracy_score(y_test, predicts))

Accuracy Test: 0.75


In [24]:
predicts = clf.predict(X_train)
print("Accuracy Train:",accuracy_score(y_train, predicts))

Accuracy Train: 1.0


Se pueden borrar las siguientes variables:
- columna 4. 
- columna 6.
- columna 7.
- columna 14.
- columna 16.

In [25]:
X = data.drop(['col4', 'y','col4','col6','col7','col14', 'col16'], axis=1)
y = data['y'].astype(int) #Según el punto 6 es la variable más explicada por las demás

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [27]:
clf = RandomForestClassifier(max_depth=3, random_state=0)
clf.fit(X_train, y_train)
predicts = clf.predict(X_test)

In [28]:
print("Accuracy Test:",metrics.accuracy_score(y_test, predicts))

Accuracy Test: 0.75


In [29]:
predicts = clf.predict(X_train)
print("Accuracy Train:",accuracy_score(y_train, predicts))

Accuracy Train: 1.0


# Punto 8